### ISSUE TITLE
ExpandMacro() should return the error message on failure

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#13]
My thinking is that it's easier to catch bugs when they announce themselves loudly, i.e. in the middle of your hypertext, with an explanation of why. Maybe even in red. :P

**Comment by invicticide** [comment]
I have this addressed in the `issue/8` branch. It will be merged back into `dev` soon-ish once I finish some other TODOs related to #8.

**Comment by invicticide** [comment]
This fix is merged into `dev` as of a43f93b
