### ISSUE TITLE
Localized markdown file support

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#14]
A language config file should be used to define separate directories for markdown files in different languages. The compiler can output multiple localized index.html files.

Guess who has two thumbs and is happy to implement this? XD

**Comment by NQNStudios** [comment]
Starting to address this in a branch of my fork: [Here](https://github.com/NQNStudios/fractive/tree/localization)

**Comment by invicticide** [comment]
Discussion on localization has moved into pull request #35
