### ISSUE TITLE
Create a nicer way to scaffold a new story project

### ISSUE THREAD

**Issue by invicticide** [invicticide/fractive#15]
Right now a new story project requires an annoying amount of manual setup:

- Create a folder
- npm install fractive
- Create a subfolder for story files, so the compiler doesn't try to compile fractive itself
- Edit package.json to create an npm build script wrapper for the super-ugly compiler CLI command
- Author all the things
- npm run build

**Comment by NQNStudios** [comment]
Since we're not supporting Webpack anymore, I'll either have to change the name of http://github.com/Natman64/fractive-webpack-template/ or make another repo for this. Unless we decide to implement scaffolding inside the fractive core toolset somehow.

I think issue #20 will prove to be relevant in this issue no matter what.

**Comment by invicticide** [comment]
I'd like to get to a place where you can do something like `fractive create <someDirectory>` and it automatically scaffolds a project there.

What does that mean?

- Creates the directory if it doesn't exist; errors out if it does, and is not empty
- Create a default build config json of some description (I'm still working out exactly what this is)
- Create default `text.md` and `script.js`

Something like that. Anyway, the first iteration would probably look more like `node lib/Create.js <someDirectory>` until I figure out how/if to compile an executable terminal app.

**Comment by invicticide** [comment]
CL 0003fa9 adds a command to `CLI.js` to do this:

```node lib/CLI.js create new/story/path```

It creates the folder structure, builds a default `fractive.json` project configuration file, copies in the basic `template.html`, and creates dummy `text.md` and `script.js` files with placeholder content, so the newly-scaffolded project is buildable/playable straightaway.

The CLI interface is still a bit suck, but at least now it exists.
