### ISSUE TITLE
Investigate webpack for story publication

### ISSUE THREAD

**Issue by invicticide** [invicticide/fractive#16]
Use webpack instead of manually gathering and concatenating all the source files?

**Comment by invicticide** [comment]
This is a pointless comment just to test the webhook

**Comment by NQNStudios** [comment]
We may not have to implement a custom markdown loader at all:

[This loader](https://github.com/pikulev/markdownattrs-loader) based on [this module](https://github.com/arve0/markdown-it-attrs) could not only compile named sections to separately identifiable HTML tags, but also enable text coloration and other styling from within story Markdown.

Variable, passage, and function inclusion would have to take on a syntax that would accommodate markdown-attrs using `{ }`. Without adding another escape sequence, maybe we distinguish Fractive-specific tags through markdown-it-attrs syntax like this:

```
**{.var #variableName}
**{.sec #sectionName}
**{.fun #functionName}
```

I know it's ugly, but it might mean not maintaining any Markdown-related code at all. Assuming I'm interpreting the module correctly, these tags should cause the HTML to output the following, which we can process in Javascript:

```
<i class="var" id="variableName"></i>
<i class="sec" id="sectionName"></i>
<i class="fun" id="functionName"></i>
```

These tags can be identified and evaluated in Core.ExpandSection() the same way they would have been previously. Classes we could use:

* .var (Display the value of the variable)
* .secBegin (Declare a section)
* .sec (Embed a section)
* .secInline (Embed a section inline)
* .fun (Embed a function's return value)
* .funInline (Embed a function inline)
* .funSilent (Call a function but do not embed)

It's possible for us to add more classes and improve readability because they don't each need a symbol.

**Comment by NQNStudios** [comment]
Here's a sequence of loaders I think would make a streamlined Fractive build chain:

0. Some kind of TypeScript linter?
1. `ts` loader loads Fractive TypeScript source files as JavaScript
2. `markdown-attrs` loads Markdown files as HTML
3. `eslint` lints the story's JavaScript files
4. `babel` transpiles the story from JavaScript ES2015 -> ES5 supported by browsers
5. Custom HTML loader loads the given template.html, filling in areas with the HTML produced by markdown-attrs, JavaScript of the Fractive core, etc.

I don't know if this makes sense, or works in practice, but it offloads a ton of the work we're currently doing onto existing & supported modules.

The Fractive repository would end up looking more like a boilerplate template for a Fractive story, that devs can download and use as a base.

In this framework, `npm start` would be the full command to deploy and build the story after cloning the repo. Relevant to #15

**Comment by NQNStudios** [comment]
This syntax for macros might be better:

`*varName*{.var}`

**Comment by invicticide** [comment]
The `markdown-it-attrs` is kind of interesting. I'd hesitate to use the `id` attribute in that way, since ids are meant to be unique identifiers within the document. We look up sections by id at runtime using `document.getElementById` which only returns the first element with that id in the document. If somebody had a section called `foo` and then did something like:

    Here's a variable value: {.var #foo}

...it becomes ambiguous which element we're going to get when we look up that id. It seems safer (though more verbose) to use a custom attribute:

    Here's a variable value: {.var name=foo}

But the sucky thing here is that these annotations need to apply to some existing element, so you'd almost need:

    Here's a variable: &nbsp;{.var name=foo}

...and then do some html postprocess to find elements of class `var` and replace them with the contents of the named variable.

I guess you could flip the syntax around per your latest comment (which posted in the middle of me typing this) like:

    Here's a variable: fooVar{.var}
    Here's a function's return value: fooFunc{.func}
    Here's a section: fooSection{.section}

That's cleaner, although I think it's still less intuitive to read since critical information now lives outside the {}, but it does give us an element for the annotation to be assigned to, the contents of which gets used to determine the assignment and then is replaced by the result of that assignment.

There's also the question of how links would work?

    [This is a link to some url](fooUrl{.var})
    [This is a section link](fooSection{.section})
    [This is a link that gets replaced inline when clicked](fooVar{.var inline=true})

These are getting kind of weird, and still rely on some html post-processing to rewrite the `<a>` tags with the relevant `onclick` actions... but it could maybe work.

I do like the annotation syntax (i.e. `{.someKeyword}` or `{.someKeyword otherStuff moreStuff}` in that it provides a more extensible convention than the current symbol-based one, but it is more verbose, and the specific implementation per `markdown-it-attrs` treats these as attributes or decorators rather than standalone replaceable macros which creates that issue of needing some element in your story text to apply the attribute *to*, even though in most cases you probably just want the attribute to simply replace itself with the appropriate generated code.

I'm kinda leaning toward forking an existing Markdown loader and then extending it with our macro syntax -- which could arguably change from `{@sectionName}` to `{.section sectionName}` or we could even support both, or other variants -- and so basically doing all our formatting shenanigans when we generate the html, rather than doing it as a postprocess on the generated html. I think that gives us more flexibility in how we define our macros and avoids issues like the `id` namespace pollution from the top of this comment.

**Comment by NQNStudios** [comment]
Yeah, I realized using `id` would be a problem soon after I closed my laptop last night 😛 

Agreed that we probably need to have more control of things. The ability to selectively apply CSS styling in story Markdown is huge, though, so we should make sure it ends up in there somehow.

Example from the markdown-it-attrs README.md:

`paragraph *style me*{.red} more text` -> `<p>paragraph <em class="red">style me</em> more text</p>`

**Comment by NQNStudios** [comment]
See https://github.com/Natman64/fractive-story-template/ for my ongoing efforts to create a Webpack-enabled story template that will resolve this issue while also (#15) creating a nicer way to scaffold a project

**Comment by NQNStudios** [comment]
My personal website is built in Jekyll which uses the Liquid template system to embed variables and perform basic logic inside Markdown files. Its syntax doesn't interfere with any Markdown syntax so we should theoretically be able to use it as a more suitable alternative to markdown-attrs.

JavaScript port: https://github.com/mattmccray/liquid.js/tree/master

Or we could use both to also gain the advantages I mentioned of in-text styling.

I'm gonna suggest closing this issue and opening two separate ones for integrating markdown-attrs and Liquid templating, without Webpack.

**Comment by invicticide** [comment]
I've pushed a `feature/webpack` branch which is a WIP integration of webpack for story bundling. It is technically in a working state but there are some dumb things which I currently consider un-shippable:

- TODO: Figure out why we need to double-dereference modules, e.g. Core.Core.SomeFunc()
- TODO: Figure out how to identify which user module to dereference for a given function/variable macro (user shouldn't have to specify this; derive it from the source filename?)
- TODO: R&D generating user module exports so the user script doesn't have to be manually wrapped and tagged like this

(This list is based on commit cc20ea8)

With that said, I don't actually... like this. You can diff `feature/webpack` against its immediate parent in `dev` to see what the webpack implementation involves, but the most illuminating thing is the diff of `examples/basic/index.html`:

    git diff --word-diff f83ace3 cc20ea8 examples/basic/index.html

This shows how the generated html changed from the old way, to the webpack way.

The script header is obviously completely different, both because the contents of Core.js had to change for webpack support, but also because the script that's being embedded is now the actual webpack output, rather than the simple file concatenation we were doing before. However, the webpacked scripts are now declared as anonymous functions which are much less accessible than the globally-declared stuff we used to have. Cool for encapsulation, I guess, but requires some pretty raw violence in user scripts to make them compatible.

The html content is identical except for reformatting links whose targets are Fractive macros; `feature/webpack` uses html data attributes to describe the behavior instead of inlining raw Javascript. I actually kinda like this, but it has nothing to do with webpack. In fact, I've cherry-picked this change into `dev` at 43d01ab.

Overall, I find webpack lacking in this use case. The compiled result isn't appreciably better (or even different) than what we had before. Webpack's dependency stripping and tree shaking could slightly reduce transfer size, but some of that is taken back by the addition of webpack's own boilerplate (the module loader, etc.), and ultimately we're talking on the order of a few kb anyway. In 2017 that seems hilariously negligible for the amount of effort and inconvenience introduced into both the Fractive development workflow and, more crucially, the end-user authoring experience. And while preventing global namespace pollution is widely accepted as valuable, I think the value in this use case is actually negligible; everything Fractive exposes is under a single object `Core` (which should probably be renamed `Fractive` at some point, but that's a separate topic) and everything else will be user scripts, which they can encapsulate however they feel like.

If anything, it seems more promising apply webpack in the *opposite* direction: create an npm package structure for your Fractive *story*, `npm install fractive` into it, then set up your own webpack configuration for packing everything (i.e. [this](https://github.com/Natman64/fractive-story-template)). At that point, webpack isn't actually being provided or supported by us at all; instead, Fractive is being used as just one dependency for some larger, enclosing webpack-enabled project. The only extent to which we might "officially" support webpack in this use case would be to provide a Fractive Markdown loader as a separate npm package from Fractive core, which webpack users could then add to their project config. Authors who are creating simple hypertext stories then needn't even be aware of any of this, and can just write simple vanilla js or even ignore js entirely. 

(And actually, this approach might not work either, because it still seems subject to the same scoping problem, i.e. "can't access webpacked scripts from the global environment in any reasonable way".)

Anyway, for all those reasons I'm calling this issue abandoned, at least for the time being.

**Comment by NQNStudios** [comment]
Still worth the plunge of experimentation, but I agree completely.
