### ISSUE TITLE
Compiler should have a .fractignore file

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#20]
Just discovered a gotcha: I had been working for Selfcare Jam without putting my story in a repo. Once I moved it into a repo, README.md in the root directory where I had put everything else, started throwing off the Compiler. Maybe we should just ignore files like README.md, code of conduct, etc?

Also: node_modules directories, .git, etc.

Maybe a .fractignore file would be a better general solution?

**Comment by invicticide** [comment]
I was thinking about this over the weekend. Part of me wonders if it's valid to use an existing .gitignore and/or .npmignore, or if there are real differences that would necessitate a .fractiveignore (or whatever).

On the other hand, I've been thinking about a build configuration json that would (among other things) allow directly specifying source paths for Markdown and Javascript files separately, which could obviate the need for any kind of ignore file. (This would also be relevant to #12)

**Comment by invicticide** [comment]
CL 0003fa9 adds a `fractive.json` project config file, the `ignore` field of which takes an array of glob patterns (.gitignore style) of files to ignore when building.
