### ISSUE TITLE
Error during npm install on Windows

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#21]
```
C:\Users\Nathaniel\fractive-story-template\fractive>npm install

> fractive@1.0.1 prepare C:\Users\Nathaniel\fractive-story-template\fractive
> npm run build


> fractive@1.0.1 build C:\Users\Nathaniel\fractive-story-template\fractive
> ./node_modules/typescript/bin/tsc

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fractive@1.0.1 build: `./node_modules/typescript/bin/tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fractive@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathaniel\AppData\Roaming\npm-cache\_logs\2017-11-06T22_05
_47_358Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fractive@1.0.1 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fractive@1.0.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathaniel\AppData\Roaming\npm-cache\_logs\2017-11-06T22_05
_47_447Z-debug.log
```

**Comment by invicticide** [comment]
Can you try editing `fractive/package.json` and changing the `build` script from `./node_modules/typescript/bin/tsc` to simply `tsc` and see if this resolves the error on Windows?

I've confirmed both forms work fine on Mac. I learned while investigating this that dependencies which install binaries (e.g. `tsc`) also install them into `node_modules/.bin`, and that folder is added to the path when running npm scripts, so the full subpath resolution is not necessary.

**Comment by invicticide** [comment]
FYI CL 69a7e72 ended up fixing this in a different way as a side effect of what I was *actually* doing, which is making `npm run build` also build the examples in addition to the Fractive core. That necessitated creating a js build script to walk all directories under `examples/` (there's just one currently, but there will more in the future).

The npm build command is now simply `node build/Build.js` which should also be portable (although to be fair, I haven't tested on Windows yet).
