### ISSUE TITLE
Resolve NPM deployment

### ISSUE THREAD

**Issue by invicticide** [invicticide/fractive#33]
The Fractive NPM package is currently out-of-date, but there are outstanding questions that need to be resolved regarding how that package is structured, published, and integrated into other projects... or if it even makes sense to continue maintaining it as such at all.

In the future I see Fractive becoming an executable application (probably inside an Electron wrapper) that functions as a story IDE. For most users, you'd just download the application and run it. Is there still a reasonable use case (e.g. for advanced extensions/integrations) to have an NPM package for which users would bypass the "official" application and just do `npm install fractive` as a dependency for some larger project? If so, what does that *really* need to look like?

**Comment by NQNStudios** [comment]
> In the future I see Fractive becoming an executable application (probably inside an Electron wrapper) that functions as a story IDE.

Maybe we should look into atom.io. We could make the Fractive editor as a plugin for that. (I've never used it but apparently it's Electron-based.)

As for the npm use-case question: So far I've enjoyed working on stories in Vim. I'm also thinking of using Scrivener for most of my writing for a while. So I do think there is a use case for fractive as an npm package for compiling externally authored stories.

**Comment by NQNStudios** [comment]
This might be of interest: I tried creating a new story as an npm package with a dependency on Fractive, and things got messy and unsatisfying pretty quickly. Here's the commit where I gave up: https://github.com/NQNStudios/beware-yon-death-trap/commit/019fff59d47b4a35b95cab32acd161fcd71ee768

`notes.md` describes the steps I took to get that far.

Even if things were structured better for an npm-based dev flow, it seems to me there would be so many steps involved that we don't want to make Fractive devs go through. I'll concede that we should make a unified editor, and that this is the npm deployment we should shoot for:

`npm install -g fractive`

**Comment by NQNStudios** [comment]
> Maybe we should look into atom.io. We could make the Fractive editor as a plugin for that. (I've never used it but apparently it's Electron-based.)

I'm now looking into this on a branch of my fork. [atom-plugin](https://github.com/NQNStudios/fractive/tree/atom-plugin)

Edit/update: I'm already getting misgivings based on how long it takes the editor to open a folder; the number of times it's crashed;  and getting overwhelmed by the plugin tutorials. Granted, it's late and I'd be better off tackling this with some energy. I also want to try SublimeText.

**Comment by NQNStudios** [comment]
Turns out SublimeText is proprietary and its plugins are written in Python, which is a lot less ideal for integration with Fractive than atom.io's JavaScript API.

**Comment by invicticide** [comment]
As of `1.1.0` this is resolved to my satisfaction. It's now possible to `npm install -g fractive` and then simply `fractive create path/to/story` and `fractive compile path/to/story`, which is good enough for non-dev users for now. If/when there's a GUI app it would replace this for those users.

For dev users -- either Fractive contributors or people making stories that use Fractive as a dependency and then wrap it with a bunch of other custom code -- they can `npm install fractive` as a local dependency like before, and it'll drop the `fractive` executable (actually a symlink to `CLI.js`) in their `node_modules/.bin` which is then trivial to wrap in some build script in their `package.json` or integrate into whatever kind of CI setup they probably have running for the larger project.

Documentation has been updated accordingly.
