### ISSUE TITLE
Section tags

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#40]
# Motivation

Twine lets developers tag every passage with arbitrary strings that can be used for sorting/processing and even exported for wrappers like UnityTwine. An example of this coming in handy is Ben Wander's [A Case of Distrust](https://forums.tigsource.com/index.php?topic=56305.msg1327516#msg1327516):

> I use Twine’s Tags feature to determine what images (characters, locations, etc) my game should be showing. For example, if we’re in a Passage that is marked with the “Butler” Tag, my code will show the butler image. If we’re in a Passage that’s marked with the “Malone’s Apartment” Tag, my code will show Malone’s apartment.

A similar system might be ideal for me in Space Bard, to mark sections with info such as which character is speaking, what portrait to use, etc. 

# Feature description

I want to be able to tag sections with a simple extension of the current syntax, i.e. `{{SomeSection: tag1, tag2}}`. Then some functions added to `Core` would be nice:

```
Core.GetTags(sectionName)
Core.GetSectionsWithTag(tag)
Core.GetCurrentSectionTags()
```

Feel free to assign me this one.

**Comment by invicticide** [comment]
It occurred to me while thinking about this that user scripts might want to be notified when the section changes. CL e599b65 adds a `Core.OnGotoSection` callback which can be assigned by user script, as seen in the new `callbacks` example. The callback passes the new section id, its DOM element, and an array of tags. The tags array is just a stub right now -- tag assignment isn't actually supported yet -- but it's illustrative of one avenue for getting this data to user scripts.

**Comment by invicticide** [comment]
PR #63 addressed this
