### ISSUE TITLE
When copying assets, need to recursively recreate folder structure

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#52]
# What happened
A file system error on Windows when putting assets inside nested folders in the Assets directory.

# Steps to reproduce
Make a new story. Create a folder inside the assets directory, and put another file in there. Then compile.

# Expected behavior
All folders inside the assets folder should be copied into the output location. Instead, they cause an error.

**Comment by invicticide** [comment]
I did this:

```
fractive create examples/nested
cd examples/nested/assets
echo foo > foo
mkdir nested
cd nested
echo bar > bar
```

Then I compiled the project, and it appears to have worked just fine. Tested in both Windows 7 and OSX.

@NQNStudios What was the specific file system error you got?

**Comment by invicticide** [comment]
Oh never mind, it looks like this only reproduces if `assets` contains only folders, no files, at its root level. Looking into a fix now.
