### ISSUE TITLE
2 enhancements to Core.GotoSection

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#55]
# What happened
I keep typing `Core.GoToSection` and not `Core.GotoSection`. I want to say this is one of those ridiculous things that doesn't matter, but sometimes it's really hard to figure out what's wrong. Can we at least get an alias for it so the typo is supported?

Another expansion that could be made simultaneously, is a convenience function for going to the same section you're currently viewing, as a way of refreshing it.

**Comment by NQNStudios** [comment]
When refreshing a section, a duplicate of the section should not be put into the history div. This causes the back button to return to the same section, which feels wrong.

**Comment by invicticide** [comment]
These enhancements are done. Note that the signature for `Core.OnGotoSection` has changed: the `isGoingBack` flag is now an instance of `Core.EGotoSectionReason` which disambiguates between goto, back, and refresh states.
