### ISSUE TITLE
npm install -g should also run build

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#56]
# What happened
I made changes to the library, and ran `npm install -g ./` to update my Fractive installation. However, the Javascript files hadn't changed, so the old library code was still executing. It seems like that command should also run the build process before updating the install.

**Comment by invicticide** [comment]
I thought this was already happening...? Unless this only occurs when installing from a local source as opposed to when installing from the npm online repository.

**Comment by NQNStudios** [comment]
I should be more specific. From the command line, when pointed to a Fractive clone, `npm install -g ./` seems to install whatever's currently in the `lib` folder, without first re-building the library such as with `npm run build`. To fix the problem, I had to run `npm run build` then run `npm install -g ./` again.
