### ISSUE TITLE
First paragraph of section disappears if directly under the section declaration

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#58]
# What happened
The first paragraph of a section I wrote wasn't appearing. I realized it was because I didn't skip a line below the section declaration.

# Steps to reproduce
Make a `text.md` like this:

```
{{Start}}
What about me, huh?

You wouldn't know it, but I am actually the second paragraph.
```

Compile and run.

# Expected behavior

These two section declarations should both be equivalent:

```
{{Start}}
First paragraph.
```

and

```
{{Start}}

First paragraph.
```

**Comment by invicticide** [comment]
This is now fixed so that all the following permutations will work as expected:

```
{{Start}}

First paragraph

Second paragraph
```

```
{{Start}}
First paragraph

Second paragraph
```

```
{{Start}}First paragraph

Second paragraph
```
