### ISSUE TITLE
Add an error message when {#function:inline} macros are used.

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#62]
Every time I go to call a function and embed the output in a section, I forget whether or not I'm supposed to declare the macro with `:inline` or not. A specific error message would be nice, because currently what happens if you do the wrong thing (`:inline`), is you get `targetFunction is undefined`, which is confusing when you know you've defined the function.

**Comment by invicticide** [comment]
That error message is obviously nonsense, so I'll look into that. But the broader issue here seems to be that `:inline` is an unclear name... I wonder if that tag should be called something different?

**Comment by NQNStudios** [comment]
Yeah, to be honest I thought I had it straight in my head and I still don't. The keyword makes the concept fuzzier in my head which makes it hard to think of a better keyword.

**Comment by NQNStudios** [comment]
To be clear, `inline` only applies to macros in link destinations and means the link itself transforms, right? Even now I'm not confident off the top of my head.

**Comment by invicticide** [comment]
Yeah, `:inline` is what you add to a link destination to say "replace the link with the expanded destination content when clicked". It has no meaning in any non-link context.

**Comment by NQNStudios** [comment]
Maybe it should just be :replace
