### ISSUE TITLE
README.md claims that building will place a binary in node_modules, but it doesn't

### ISSUE THREAD

**Issue by audiodude** [invicticide/fractive#84]
# Steps to reproduce
```
$ npm run build

> fractive@1.3.1 build <redacted>/fractive
> node build/Build.js

Generating type declarations...
Building engine...
Building documentation...
Building examples...
  basic (1/6)
  callbacks (2/6)
  link-tags (3/6)
  macros (4/6)
  refresh (5/6)
  section-tags (6/6)

Build finished in 7.46 seconds

$ ls node_modules/.bin/
commonmark	esvalidate	js-beautify	nopt		tsserver
css-beautify	he		js-yaml		prettier	uglifyjs
editorconfig	html-beautify	json2ts		semver
esparse		html-minifier	mkdirp		tsc
```

# Expected behavior
There is a fractive binary at `./node_modeules/.bin/fractive`, as stated in the README

# Actual behavior
No binary exists. I noticed that the Build.js script is using `node lib/CLI.js compile` to compile the documentation examples.

**Comment by invicticide** [comment]
CL e15c6a3 updates the readme with accurate information. (Granted, this build process could still be easier than it is...)
