### ISSUE TITLE
Offsite links should open in a new window and show an icon

### ISSUE THREAD

**Issue by invicticide** [invicticide/fractive#9]
Links that go to some offsite address (as opposed to a Fractive macro destination) should open in a new window/tab, and should display a little "offsite" icon after the link, like you'd see on Wikipedia or whatever.

Might also want to control this on a per-story basis in a settings.json or something.

**Comment by NQNStudios** [comment]
I could potentially tackle this using the `html-ast-transform` library I used to experiment with markdown-it-attrs [here](https://github.com/NQNStudios/fractive/blob/attributes/src/Compiler.ts).

Rather than restructure everything not to use CommonMark, we can use `html-ast-transform` as a second compilation step, which would identify off-site links, add an external link icon, and set their `target` attribute to `_blank`.

As long as you're ok with adding another AST dependency, I think this would be a clean way to do it.

**Comment by invicticide** [comment]
I'm not *super* excited about building and transforming a second AST, tbh. Even though `html-ast-transform` does look nice, on its own merits.

**Comment by NQNStudios** [comment]
I'm pretty sure I was assuming the original AST flow couldn't do this step for some reason, but that's definitely not the case, right? I might be able to close this one today

**Comment by invicticide** [comment]
We turn `link` nodes into `html_inline` nodes during the Commonmark AST transform. Since we're crafting raw html for the link, it should be trivial to add an `<img>` tag there. I'd look in `Compiler.RenderLink`, and possibly just pass an (optional) image argument from there to `Compiler.RewriteLinkNode`, which could then be embedded inside the newly-written `<a>` tag, after the link text.

The real question is, what are the icons, where are they sourced from, are they associated with a template or otherwise themable/replaceable, etc.

I had the notion to look into SVG icons so they antialias nicely when scaled down but can still retain sharpness on Retina displays.

**Comment by NQNStudios** [comment]
I had always thought that Wikipedia's external link icon was standard and a part of Unicode, but I guess not. https://en.m.wikipedia.org/wiki/Help:External_link_icons

This brings up another interesting idea which is, should we have file type icons, too? I don't see myself including hella PDF downloads in my games but you never know.

**Comment by NQNStudios** [comment]
I have a plan to implement this: define "external-link-mark" in fractive.json and insert whatever value is stored there as raw HTML. The developer can use a custom image by making it an <IMG> tag, or, as I plan on doing:

Include fontawesome in the template HTML, and use the symbol for external links that they provide.

http://fontawesome.io/icons/

So we don't have to ship any icons with fractive. If anyone doesn't want to depend on fontawesome they can make their own template; its inclusion is just a script tag in the HTML.

**Comment by NQNStudios** [comment]
I don't remember if it was this way back when I installed the font on my website, but apparently it associates every embed widget with an email address. I'll start by implementing with my own email, but if you like the fontawesome approach maybe we should make an official fractive email.

**Comment by invicticide** [comment]
Addressed by PR #37
